// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV4_CzVDCyMiKh133VnyXFE__vCKStB2c',
    appId: '1:795172916667:web:96e31bd2902b05e287089e',
    messagingSenderId: '795172916667',
    projectId: 'fasum-d8148',
    authDomain: 'fasum-d8148.firebaseapp.com',
    storageBucket: 'fasum-d8148.firebasestorage.app',
    measurementId: 'G-5E3PRBHN7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHjLBAus41uu-tkrw0TdjqVnX6u359ujo',
    appId: '1:795172916667:android:737322d345caf84187089e',
    messagingSenderId: '795172916667',
    projectId: 'fasum-d8148',
    storageBucket: 'fasum-d8148.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV4_CzVDCyMiKh133VnyXFE__vCKStB2c',
    appId: '1:795172916667:web:e68126536697f01387089e',
    messagingSenderId: '795172916667',
    projectId: 'fasum-d8148',
    authDomain: 'fasum-d8148.firebaseapp.com',
    storageBucket: 'fasum-d8148.firebasestorage.app',
    measurementId: 'G-BSPZVMPHV1',
  );

}