// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApTN5RqLPG_pkJN5UnPYfsrl7agKFx-a8',
    appId: '1:6921536955:web:7fd45ef7eb15387cd5b09e',
    messagingSenderId: '6921536955',
    projectId: 'first-app-9fabc',
    authDomain: 'first-app-9fabc.firebaseapp.com',
    databaseURL: 'https://first-app-9fabc-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-9fabc.firebasestorage.app',
    measurementId: 'G-XCGNZVXYBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5GsgsvvOXnlZzD4c736gRM4KWO0BrqLU',
    appId: '1:6921536955:android:14b4a849db468492d5b09e',
    messagingSenderId: '6921536955',
    projectId: 'first-app-9fabc',
    databaseURL: 'https://first-app-9fabc-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-9fabc.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApTN5RqLPG_pkJN5UnPYfsrl7agKFx-a8',
    appId: '1:6921536955:web:5b7a9ad5fcbabca0d5b09e',
    messagingSenderId: '6921536955',
    projectId: 'first-app-9fabc',
    authDomain: 'first-app-9fabc.firebaseapp.com',
    databaseURL: 'https://first-app-9fabc-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-9fabc.firebasestorage.app',
    measurementId: 'G-SSFLGXDK1D',
  );
}
